name: Teste com Jest

on:
  push:
    branchs: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Rodar testes com Jest
        run: npm test

    deploy:
      runs-on: ubuntu-latest
      needs: test

      steps:
        - name: Simular deploy
          run: echo "Deploy realizado com sucesso"